package lint

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/larsartmann/go-finding"
)

// writeTree writes files (relative path -> content) under a fresh temp dir
// and returns the dir. The classic fixture helper for the rule tests.
func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()

	dir := t.TempDir()

	for rel, content := range files {
		path := filepath.Join(dir, rel)

		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", rel, err)
		}

		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("write %s: %v", rel, err)
		}
	}

	return dir
}

// ruleIDsOf extracts the sorted-unique rule IDs of a finding set.
func ruleIDsOf(t *testing.T, findings []finding.Finding) []string {
	t.Helper()

	seen := map[string]bool{}
	ids := []string{}

	for _, f := range findings {
		if !seen[string(f.Rule)] {
			seen[string(f.Rule)] = true
			ids = append(ids, string(f.Rule))
		}
	}

	return ids
}

func TestAnalyzeSkipsVendorTestdataAndGenerated(t *testing.T) {
	t.Parallel()

	dir := writeTree(t, map[string]string{
		"main.go":             "package main\n",
		"vendor/lib/lib.go":   "package lib\n",
		"testdata/fixture.go": "package fixture\n",
		".hidden/skip.go":     "package hidden\n",
		"gen/gen.go":          "// Code generated by tool. DO NOT EDIT.\npackage gen\n",
		"broken/broken.go":    "this is not go source",
	})

	proj, err := analyze(context.Background(), dir)
	if err != nil {
		t.Fatalf("analyze: %v", err)
	}

	if len(proj.files) != 1 {
		t.Fatalf("expected 1 parsed file, got %d", len(proj.files))
	}

	if proj.files[0].relPath != "main.go" {
		t.Errorf("expected main.go, got %s", proj.files[0].relPath)
	}

	if len(proj.skipped) != 1 {
		t.Errorf("expected broken.go recorded as skipped, got %v", proj.skipped)
	}
}

func TestAnalyzeResolvesAliasesAndMajors(t *testing.T) {
	t.Parallel()

	dir := writeTree(t, map[string]string{
		"aliased.go": "package main\n\nimport cmdguard \"github.com/larsartmann/cmdguard/v3/pkg/cmdguard/v3\"\n\nvar _ = cmdguard.NoFlags{}\n",
		"plain.go":   "package other\n\nimport \"github.com/larsartmann/cmdguard/v4/pkg/cmdguard/v4\"\n\nvar _ = v4.NoFlags{}\n",
		"none.go":    "package none\n\nimport \"fmt\"\n\nvar _ = fmt.Println\n",
	})

	proj, err := analyze(context.Background(), dir)
	if err != nil {
		t.Fatalf("analyze: %v", err)
	}

	if !proj.importsCmdguard {
		t.Error("expected importsCmdguard")
	}

	var aliased, plain *sourceFile

	for i := range proj.files {
		switch proj.files[i].relPath {
		case "aliased.go":
			aliased = &proj.files[i]
		case "plain.go":
			plain = &proj.files[i]
		}
	}

	if aliased == nil || plain == nil {
		t.Fatal("expected aliased.go and plain.go to be parsed")
	}

	if got := aliased.imports["cmdguard"]; got != "github.com/larsartmann/cmdguard/v3/pkg/cmdguard/v3" {
		t.Errorf("aliased import resolution: got %q", got)
	}

	if aliased.cmdguardMajor != "v3" {
		t.Errorf("aliased major: got %q, want v3", aliased.cmdguardMajor)
	}

	// Unaliased v4 import resolves to the package name "v4" (last segment).
	if got := plain.imports["v4"]; got != "github.com/larsartmann/cmdguard/v4/pkg/cmdguard/v4" {
		t.Errorf("plain import resolution: got %q", got)
	}

	if plain.cmdguardMajor != "v4" {
		t.Errorf("plain major: got %q, want v4", plain.cmdguardMajor)
	}
}

func TestMajorOf(t *testing.T) {
	t.Parallel()

	tests := []struct {
		path string
		want string
	}{
		{"github.com/larsartmann/cmdguard", "v1"},
		{"github.com/larsartmann/cmdguard/v3/pkg/cmdguard/v3", "v3"},
		{"github.com/larsartmann/cmdguard/v4/pkg/cmdguard/v4", "v4"},
		{"github.com/larsartmann/cmdguard/spinner", ""},
		{"github.com/larsartmann/cmdguard/telemetry", ""},
		{"example.com/other/v2", ""},
	}

	for _, test := range tests {
		if got := majorOf(test.path); got != test.want {
			t.Errorf("majorOf(%q) = %q, want %q", test.path, got, test.want)
		}
	}
}

func TestPackageNameFor(t *testing.T) {
	t.Parallel()

	tests := []struct {
		path string
		want string
	}{
		{"go.uber.org/multierr", "multierr"},
		{"golang.org/x/sync/errgroup", "errgroup"},
		{"example.com/lib/v2", "lib"},
	}

	for _, test := range tests {
		if got := packageNameFor(test.path); got != test.want {
			t.Errorf("packageNameFor(%q) = %q, want %q", test.path, got, test.want)
		}
	}
}

func TestAnalyzeCacheReusesAndClears(t *testing.T) {
	t.Parallel()

	dir := writeTree(t, map[string]string{"a.go": "package a\n"})

	first, err := analyze(context.Background(), dir)
	if err != nil {
		t.Fatalf("analyze: %v", err)
	}

	ClearCache()

	second, err := analyze(context.Background(), dir)
	if err != nil {
		t.Fatalf("analyze after clear: %v", err)
	}

	if first == second {
		t.Error("expected a fresh project after ClearCache, got the cached instance")
	}
}
